#!/usr/bin/env bash

configure_tmux(){
    plugins_dir="$HOME/.tmux/plugins"
    echo "Configuring tmux..."
    if [ ! -d "$plugins_dir" ]; then
        echo "Installing plugins..."
        mkdir -p "$plugins_dir"
        git clone https://github.com/tmux-plugins/tpm "$plugins_dir/tpm"
        ~/.tmux/plugins/tpm/bin/install_plugins
    fi
}

configure_tmux
