#!/usr/bin/env bash

configure_tmux(){
    plugins_dir="$HOME/.tmux/plugins"
    echo "Configuring tmux..."
    if [ ! -d "$plugins_dir" ]; then
        echo "Installing plugins..."
        mkdir -p "$plugins_dir"
        git clone https://github.com/tmux-plugins/tpm "$plugins_dir/tpm"
        ~/.tmux/plugins/tpm/bin/install_plugins
    fi
}

configure_neovim(){
    echo "Configuring neovim..."
    if [ ! -d "~/.local/share/nvim/site/pack/packer/" ]; then
        git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    fi

    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
}

configure_tmux
configure_neovim
