#!/usr/bin/env bash

packages="zsh tmux emacs neovim firefox mpv sxiv virt-manager mpd sxhkd feh cinnamon fzf aerc xclip weechat unzip zathura build-essential golang python3 curl"

mint_setup(){
    echo "Setting up for Linux Mint..."

    sudo add-apt-repository ppa:neovim-ppa/stable
    sudo add-apt-repository ppa:kelleyk/emacs

    sudo apt-get update
    sudo apt-get upgrade

    sudo apt-get install "$packages"
}

debian_setup(){
    echo "Setting up for Debian..."

    sudo apt-get update
    sudo apt-get upgrade

    sudo apt-get install "$packages"
}

configure_zsh(){
    echo "Configuring zsh..."

    if [ "$SHELL" != $(which zsh) ]; then
        chsh -s "$(which zsh)"
    fi

    if [ ! -d "$HOME/.zplug" ]; then
        echo "Installing zplug..."
        git clone https://github.com/zplug/zplug "$HOME/.zplug"
    fi
}

case $(lsb_release -is) in
    [Ll]inux[Mm]int)
        mint_setup
        ;;
    [Dd]ebian)
        debian_setup
        ;;
esac

configure_zsh

./setup-home
./create-symlinks
./configure-applications
