#!/usr/bin/env bash

packages="tmux neovim fzf aerc findutils make gpg"
cask_packages="emacs kitty"

if ! command -v brew &> /dev/null
then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew install $packages
brew install --cask $cask_packages

./setup-home
./create-symlinks
./configure-applications
