#!/usr/bin/env bash

packages="tmux neovim fzf aerc findutils make gpg go python wezterm"
cask_packages="emacs"

if ! command -v brew &> /dev/null
then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew install $packages
brew install --cask $cask_packages

mkdir -p ~/src
mkdir -p ~/mail

./configure-applications
./create-symlinks
