#!/usr/bin/env bash

packages="zsh tmux emacs neovim firefox mpv sxiv virt-manager mpd sxhkd feh cinnamon fzf"

pkg_manager=""
case $(lsb_release -is) in
    [Vv]oid[Ll]inux)
        pkg_manager="xbps-install -S"
        ;;
    [Ll]inux[Mm]int)
        pkg_manager="apt-get install"
        ;;
esac

install(){
    sudo $pkg_manager "$@"
}

configure_zsh(){
    echo "Configuring zsh..."

    if [ "$SHELL" != $(which zsh) ]; then
        chsh -s "$(which zsh)"
    fi

    if [ ! -d "$HOME/.zplug" ]; then
        echo "Installing zplug..."
        git clone https://github.com/zplug/zplug "$HOME/.zplug"
    fi
}

install $packages

configure_zsh

./setup-home
./create-symlinks
./configure-applications
