#!/bin/sh

alias E="SUDO_EDITOR=\"emacs\" sudoedit"
alias vim="nvim"
alias e="emacs"
alias v="vim"
alias V="SUDO_EDITOR=\"vim\" sudoedit"
alias gpg="gpg2"
alias nnn="nnn -R"

alias ls="ls --color=auto"
alias la="ls -Alh"
alias ll="ls -lhF"
alias df="df -kTh"
alias du="du -h"

alias rm="rm -i"
alias mv="mv -i"

alias pkgs="xbps-query -l"
alias \?="duck"

# git

alias gs="git status"
alias gss="git status -b --short"
alias gd="git diff"
alias gl="git log"

# directories

alias b="cd ~/bin"
alias s="cd ~/src"
alias d="cd ~/src/dotfiles"
alias h="cd"
