#! /bin/sh

sxhkd &
compton &
dunst &

feh --bg-scale ~/media/pics/wallpaper/dwight_quote.jpg

bspc monitor -d web code chat music misc

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follow_pointer false

bspc rule -a firefox desktop=^1
bspc rule -a utox desktop=^3
bspc rule -a discord desktop=^3
bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
