#!/bin/bash

[[ ! $(pidof -x sxhkd) ]] && sxhkd &
[[ ! $(pidof -x compton) ]] && compton &
[[ ! $(pidof -x dunst) ]] && dunst &
[[ ! $(pidof -x xautolock) ]] && xautolock -time 10 -locker slock &

feh --bg-scale ~/media/pics/wallpaper/dwight_quote.jpg

padding=5

bspc monitor HDMI-0 -d web code games
bspc monitor HDMI-1 -d chat music misc

bspc config border_width              3
bspc config window_gap                10

for side in top right right bottom left; do
	bspc config ${side}_padding $padding
done

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_follows_pointer     false

bspc rule -a firefox desktop=web
bspc rule -a utox desktop=chat
bspc rule -a discord desktop=chat
bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop=code state=tiled follow=on

. ~/.config/bspwm/polybar_launch.sh
